// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppaovcngntycdxqxbjui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwYW92Y25nbnR5Y2R4cXhianVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNjM3NjksImV4cCI6MjA1NzYzOTc2OX0.unneFVx2oD_SmJDkHtcAFTwOl-9P_QnoyT0CO7Xq0lE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
